In [1]:
import pandas as pd

In [26]:
df = pd.read_csv("data/jre_elon_musk.csv")
df.head()

    Timestamp    Speaker                                               Text
0  [00:00:00]  Joe Rogan  Ah, ha, ha, ha. Four, three, two, one, boom. T...
1  [00:00:09]  Elon Musk                                    You're welcome.
2  [00:00:10]  Joe Rogan                        It's very good to meet you.
3  [00:00:11]  Elon Musk                              Nice to meet you too.
4  [00:00:12]  Joe Rogan    And thanks for not lighting this place on fire.

In [4]:
for i in range(10):
    print(df.Text[i])

Ah, ha, ha, ha. Four, three, two, one, boom. Thank you. Thanks for doing this, man. Really appreciate it.
You're welcome.
It's very good to meet you.
Nice to meet you too.
And thanks for not lighting this place on fire.
You're welcome. That's coming later.
How does one, just in the middle of doing all the things you do, create cars, rockets, all the stuff you're doing,constantly innovating, decide to just make a flamethrower? Where do you have the time for that?
Well, the flame, we didn't put a lot of time into the flamethrower. This was an off-the-cuff thing. It's sort of a hobbycompany called the Boring Company, which started out as a joke, and we decided to make a real, and dig a tunnelunder LA. And then, other people asked us to dig tunnels. And so, we said yes in a few cases.
Now, who-
And then, we have a merchandise section that only has one piece of merchandise at a time. And we started off witha cap. And there was only one thing on, which is BoringCompany.com/hat. That's it. And then, we sold the hats,limited edition. It just said, "The Boring Company."

In [3]:
# Print the first ten lines of text

Ah, ha, ha, ha. Four, three, two, one, boom. Thank you. Thanks for doing this, man. Really appreciate it.
You're welcome.
It's very good to meet you.
Nice to meet you too.
And thanks for not lighting this place on fire.
You're welcome. That's coming later.
How does one, just in the middle of doing all the things you do, create cars, rockets, all the stuff you're doing,constantly innovating, decide to just make a flamethrower? Where do you have the time for that?
Well, the flame, we didn't put a lot of time into the flamethrower. This was an off-the-cuff thing. It's sort of a hobbycompany called the Boring Company, which started out as a joke, and we decided to make a real, and dig a tunnelunder LA. And then, other people asked us to dig tunnels. And so, we said yes in a few cases.
Now, who-
And then, we have a merchandise section that only has one piece of merchandise at a time. And we started off witha cap. And there was only one thing on, which is BoringCompany.com/hat. That's it. And then, we sold the hats,limited edition. It just said, "The Boring Company."
And then, I'm a big fan of Spaceballs, the movie. And in Spaceballs, Yogurt goes through the merchandisingsection, and they have a flamethrower in the merchandising section of Spaceballs. And, like, the kids love that one.That's the line when he pulls up the flamethrower. It's like, "We should do a flamethrower." So, we-

In [40]:
# Create a function to convert timestamp into seconds
import re
def convert_timestamp_into_seconds(timestamp):
    regex_number_finder = "\d+"
    temp_list = re.findall(regex_number_finder, timestamp)
    seconds = int(temp_list[0])*3600 + int(temp_list[1])*60 + int(temp_list[2])

    return seconds


    
    # your code here

In [45]:
# Convert the Timestamp column using the function defined above
df_copy = df.copy()

In [46]:
df_copy['New_Timestamp'] = df_copy['Timestamp'].apply(lambda x: convert_timestamp_into_seconds(x))
df_copy

,Timestamp,Speaker,Text,New_Timestamp
0,[00:00:00],Joe Rogan,"Ah, ha, ha, ha. Four, three, two, one, boom. T...",0
1,[00:00:09],Elon Musk,You're welcome.,9
2,[00:00:10],Joe Rogan,It's very good to meet you.,10
3,[00:00:11],Elon Musk,Nice to meet you too.,11
4,[00:00:12],Joe Rogan,And thanks for not lighting this place on fire.,12
...,...,...,...,...
1826,[02:36:41],Joe Rogan,"I believe it's true too. So, thank you.",9401
1827,[02:36:43],Elon Musk,You're welcome.,9403
1828,[02:36:44],Joe Rogan,"All you assholes out there, be nice. Be nice, ...",9404
1829,[02:36:50],Elon Musk,"All right, thank you.",9410
1830,[02:36:50],Joe Rogan,"Good night, everybody. END OF TRANSCRIPTAutoma...",9410

In [47]:
=

(1831, 3)

In [94]:
# Add a column with the seconds lasted by the text in the row
# for example: the first row lasts 9 seconds, since Elon Musk
# answer at the second 9 (Hint: use shift with period - 1).
# In case of negative numbers, just make them 1 (minimum interval lenght is 1 second)
import numpy as np
def max1(x):
    return np.maximum(1,x)


for i in range(df_copy.shape[0]-1):
    df_copy['Interval'][i] = max1(df_copy['New_Timestamp'][i+1]-df_copy['New_Timestamp'][i])
df_copy['Interval'][1830] = 1

df_copy

<ipython-input-94-fec412f7bb33>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Interval'][i] = max1(df_copy['New_Timestamp'][i+1]-df_copy['New_Timestamp'][i])
<ipython-input-94-fec412f7bb33>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy['Interval'][1830] = 1

,Timestamp,Speaker,Text,New_Timestamp,Interval
0,[00:00:00],Joe Rogan,"Ah, ha, ha, ha. Four, three, two, one, boom. T...",0,9
1,[00:00:09],Elon Musk,You're welcome.,9,1
2,[00:00:10],Joe Rogan,It's very good to meet you.,10,1
3,[00:00:11],Elon Musk,Nice to meet you too.,11,1
4,[00:00:12],Joe Rogan,And thanks for not lighting this place on fire.,12,1
...,...,...,...,...,...
1826,[02:36:41],Joe Rogan,"I believe it's true too. So, thank you.",9401,2
1827,[02:36:43],Elon Musk,You're welcome.,9403,1
1828,[02:36:44],Joe Rogan,"All you assholes out there, be nice. Be nice, ...",9404,6
1829,[02:36:50],Elon Musk,"All right, thank you.",9410,1
1830,[02:36:50],Joe Rogan,"Good night, everybody. END OF TRANSCRIPTAutoma...",9410,1

9

In [9]:
df.Speaker.unique()

array(['Joe Rogan', 'Elon Musk', 'Jaime'], dtype=object)

In [61]:
# Total seconds spoken by Joe Rogan
Joe_Rogan_seconds = df_copy[df_copy['Speaker']=='Joe Rogan']['Interval'].sum()
Joe_Rogan_seconds

4488

In [63]:
# Total seconds spoken by Elon Musk

Elon_Musk_seconds = df_copy[df_copy['Speaker']=='Elon Musk']['Interval'].sum()
Elon_Musk_seconds

4882

In [64]:
# Total seconds spoken by Jaime

Jaime_seconds = df_copy[df_copy['Speaker']=='Jaime']['Interval'].sum()
Jaime_seconds

40

In [67]:
# Average speaking interval for each person

Joe_Rogan_seconds_avg = df_copy[df_copy['Speaker']=='Joe Rogan']['Interval'].mean()
Elon_Musk_seconds_avg = df_copy[df_copy['Speaker']=='Elon Musk']['Interval'].mean()
Jaime_seconds_avg = df_copy[df_copy['Speaker']=='Jaime']['Interval'].mean()

print(f'Average Joe Rogan Length : {Joe_Rogan_seconds_avg} s')
print(f'Average Elon Musk Length : {Elon_Musk_seconds_avg} s')
print(f'Average Jaime Length : {Jaime_seconds_avg} s')

Average Joe Rogan Length : 4.9591160220994475 s
Average Elon Musk Length : 5.370737073707371 s
Average Jaime Length : 2.3529411764705883 s

Who speaks faster?

Tokenize the text, preprocess the tokens so that you have only words (excluding punctuation) and compute the velocity of each speaker as: number of words per interval / length of interval . Store the result in a column named Velocity and compute the average for each speaker.

In [70]:
# Preprocess the data
import spacy

nlp = spacy.load("en_core_web_sm")

In [90]:


# Create a function to remove punctuation from text

def remove_punctuation(text):
    doc = nlp(text)
    token_list = [token for token in doc if not token.is_punct]
    no_punct_sentence = ' '.join(token.text for token in token_list)
    return no_punct_sentence

# Create a function to count the non punctuation token of a text

def count_tokens(text):
    doc = nlp(text)
    token_count = len(doc)
    return token_count
    
# Create a function to remove stop words from text
    
def remove_stopwords(text):
    doc = nlp(text)
    token_list = [token for token in doc if not token.is_punct]
    filtered_list = []
    for token in token_list:
        if token.text in nlp.Defaults.stop_words == False:
            filtered_list.append(token)

    no_stopword_sentence = ' '.join(token.text for token in filtered_list)
    return no_stopword_sentence

In [98]:
# CALL THE FUNCTIONS

df_copy["TextNoPunct"] = df_copy['Text'].apply(lambda x: remove_punctuation(x))
df_copy["n_tokens"] = df_copy['Text'].apply(lambda x: count_tokens(x))
df_copy["TextNoStopword"] = df_copy['Text'].apply(lambda x: remove_stopwords(x))

In [99]:
df_copy

,Timestamp,Speaker,Text,New_Timestamp,Interval,TextNoPunct,n_tokens,TextNoStopword
0,[00:00:00],Joe Rogan,"Ah, ha, ha, ha. Four, three, two, one, boom. T...",0,9,Ah ha ha ha Four three two one boom Thank you ...,32,
1,[00:00:09],Elon Musk,You're welcome.,9,1,You 're welcome,4,
2,[00:00:10],Joe Rogan,It's very good to meet you.,10,1,It 's very good to meet you,8,
3,[00:00:11],Elon Musk,Nice to meet you too.,11,1,Nice to meet you too,6,
4,[00:00:12],Joe Rogan,And thanks for not lighting this place on fire.,12,1,And thanks for not lighting this place on fire,10,
...,...,...,...,...,...,...,...,...
1826,[02:36:41],Joe Rogan,"I believe it's true too. So, thank you.",9401,2,I believe it 's true too So thank you,12,
1827,[02:36:43],Elon Musk,You're welcome.,9403,1,You 're welcome,4,
1828,[02:36:44],Joe Rogan,"All you assholes out there, be nice. Be nice, ...",9404,6,All you assholes out there be nice Be nice bit...,27,
1829,[02:36:50],Elon Musk,"All right, thank you.",9410,1,All right thank you,6,
1830,[02:36:50],Joe Rogan,"Good night, everybody. END OF TRANSCRIPTAutoma...",9410,1,Good night everybody END OF TRANSCRIPTAutomate...,21,

In [16]:
df

,Timestamp,Speaker,Text,Interval,TextNoPunct,n_tokens
0,0,Joe Rogan,"Ah, ha, ha, ha. Four, three, two, one, boom. T...",9.0,Ah ha ha ha Four three two one boom Thank you ...,19
1,9,Elon Musk,You're welcome.,1.0,You 're welcome,3
2,10,Joe Rogan,It's very good to meet you.,1.0,It 's very good to meet you,7
3,11,Elon Musk,Nice to meet you too.,1.0,Nice to meet you too,5
4,12,Joe Rogan,And thanks for not lighting this place on fire.,1.0,And thanks for not lighting this place on fire,9
...,...,...,...,...,...,...
1826,2921,Joe Rogan,"I believe it's true too. So, thank you.",2.0,I believe it 's true too So thank you,9
1827,2923,Elon Musk,You're welcome.,1.0,You 're welcome,3
1828,2924,Joe Rogan,"All you assholes out there, be nice. Be nice, ...",6.0,All you assholes out there be nice Be nice bit...,18
1829,2930,Elon Musk,"All right, thank you.",1.0,All right thank you,4
1830,2930,Joe Rogan,"Good night, everybody. END OF TRANSCRIPTAutoma...",1.0,Good night everybody END OF TRANSCRIPTAutomate...,17

In [107]:
# Compute the velocity and store it in a new column


df_copy["Velocity"] = df_copy['n_tokens']/df_copy['Interval']
df_copy

,Timestamp,Speaker,Text,New_Timestamp,Interval,TextNoPunct,n_tokens,TextNoStopword,Velocity
0,[00:00:00],Joe Rogan,"Ah, ha, ha, ha. Four, three, two, one, boom. T...",0,9,Ah ha ha ha Four three two one boom Thank you ...,32,,3.555556
1,[00:00:09],Elon Musk,You're welcome.,9,1,You 're welcome,4,,4.000000
2,[00:00:10],Joe Rogan,It's very good to meet you.,10,1,It 's very good to meet you,8,,8.000000
3,[00:00:11],Elon Musk,Nice to meet you too.,11,1,Nice to meet you too,6,,6.000000
4,[00:00:12],Joe Rogan,And thanks for not lighting this place on fire.,12,1,And thanks for not lighting this place on fire,10,,10.000000
...,...,...,...,...,...,...,...,...,...
1826,[02:36:41],Joe Rogan,"I believe it's true too. So, thank you.",9401,2,I believe it 's true too So thank you,12,,6.000000
1827,[02:36:43],Elon Musk,You're welcome.,9403,1,You 're welcome,4,,4.000000
1828,[02:36:44],Joe Rogan,"All you assholes out there, be nice. Be nice, ...",9404,6,All you assholes out there be nice Be nice bit...,27,,4.500000
1829,[02:36:50],Elon Musk,"All right, thank you.",9410,1,All right thank you,6,,6.000000
1830,[02:36:50],Joe Rogan,"Good night, everybody. END OF TRANSCRIPTAutoma...",9410,1,Good night everybody END OF TRANSCRIPTAutomate...,21,,21.000000

In [18]:
df

,Timestamp,Speaker,Text,Interval,TextNoPunct,n_tokens,Velocity
0,0,Joe Rogan,"Ah, ha, ha, ha. Four, three, two, one, boom. T...",9.0,Ah ha ha ha Four three two one boom Thank you ...,19,2.111111
1,9,Elon Musk,You're welcome.,1.0,You 're welcome,3,3.000000
2,10,Joe Rogan,It's very good to meet you.,1.0,It 's very good to meet you,7,7.000000
3,11,Elon Musk,Nice to meet you too.,1.0,Nice to meet you too,5,5.000000
4,12,Joe Rogan,And thanks for not lighting this place on fire.,1.0,And thanks for not lighting this place on fire,9,9.000000
...,...,...,...,...,...,...,...
1826,2921,Joe Rogan,"I believe it's true too. So, thank you.",2.0,I believe it 's true too So thank you,9,4.500000
1827,2923,Elon Musk,You're welcome.,1.0,You 're welcome,3,3.000000
1828,2924,Joe Rogan,"All you assholes out there, be nice. Be nice, ...",6.0,All you assholes out there be nice Be nice bit...,18,3.000000
1829,2930,Elon Musk,"All right, thank you.",1.0,All right thank you,4,4.000000
1830,2930,Joe Rogan,"Good night, everybody. END OF TRANSCRIPTAutoma...",1.0,Good night everybody END OF TRANSCRIPTAutomate...,17,17.000000

In [108]:
# Inspect the avg velocity of each speaker

Joe_Rogan_velocity_avg = df_copy[df_copy['Speaker']=='Joe Rogan']['Velocity'].mean()
Elon_Musk_velocity_avg = df_copy[df_copy['Speaker']=='Elon Musk']['Velocity'].mean()
Jaime_velocity_avg = df_copy[df_copy['Speaker']=='Jaime']['Velocity'].mean()

print(f'Average Joe Rogan Velocity : {Joe_Rogan_velocity_avg} s')
print(f'Average Elon Musk Velocity : {Elon_Musk_velocity_avg} s')
print(f'Average Jaime Velocity : {Jaime_velocity_avg} s')

Average Joe Rogan Velocity : 3.8879052740962035 s
Average Elon Musk Velocity : 3.7574319240827343 s
Average Jaime Velocity : 4.749742002063984 s

After all, Elon was high...

![image](https://bsmedia.business-standard.com/_media/bs/img/article/2018-09/09/full/1536463138-6668.jpg)

In [ ]:
#